[package]
name = "x509-cert-test-support"
description = """
Set of utils to run certificates through zlint or openssl.
"""
version = "0.1.0"
edition = "2021"
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
homepage = "https://github.com/RustCrypto/formats/tree/master/x509-cert/test-support"
repository = "https://github.com/RustCrypto/formats"
categories = ["cryptography"]
readme = "README.md"

[dependencies]
serde = { version = "1.0.184", features = ["derive"] }
serde_json = "1"
tempfile = "3"
