[package]
name = "x509-ext"
version = "0.1.0" # Also update html_root_url in lib.rs when bumping this
edition = "2021"
description = "Pure Rust implementation X.509 Extensions"
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
repository = "https://github.com/RustCrypto/formats/tree/master/x509-ext"
categories = ["cryptography", "data-structures", "encoding", "no-std"]
keywords = ["crypto", "X.509", "extensions"]
readme = "README.md"
rust-version = "1.56"

[dev-dependencies]
hex-literal = "0.3"

[dependencies]
der = { version = "=0.6.0-pre.1", features = ["derive", "alloc", "oid"], path = "../der" }

[features]
std = ["der/std"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
