[package]
name = "x509-fuzz"
version = "0.0.0"
authors = ["RustCrypto Developers"]
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
x509-cert = { path = ".." }

# Prevents this crate from interfering with the workspace
[workspace]
members = ["."]
