name: pkcs10

on:
  pull_request:
    paths:
      - "base64ct/**"
      - "const-oid/**"
      - "der/**"
      - "pem-rfc7468/**"
      - "pkcs10/**"
      - "spki/**"
      - "x501/**"
      - "x509/**"
      - "Cargo.*"
  push:
    branches: master

defaults:
  run:
    working-directory: pkcs10

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.57.0 # MSRV
          - stable
        target:
          - thumbv7em-none-eabi
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
      - run: cargo build --release --target ${{ matrix.target }} --no-default-features
      - run: cargo build --release --target ${{ matrix.target }} --no-default-features --features pem

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.57.0 # MSRV
          - stable
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - run: cargo test --release --no-default-features
      - run: cargo test --release
      - run: cargo test --release --features pem
      - run: cargo test --release --all-features
