name: Security Audit
on:
  pull_request:
    paths:
      - "Cargo.lock"
      - ".github/workflows/security-audit.yml"
  push:
    branches: master
    paths:
      - "Cargo.lock"
      - ".github/workflows/security-audit.yml"
  schedule:
    - cron: "0 0 * * *"

jobs:
  security_audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: actions/cache@v4
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-audit-v0.21.2
      - uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

